CREATE TABLE ZEFA
(COLI NUMBER(6));
 
INSERT INTO ZEFA VALUES (1);
 
COMMIT; --EXEMPLO
 
--LER A TABELA DESSE USUARIO
SELECT * FROM PF0844.ZEFA;
 
--Conceder previlegio
GRANT SELECT ON ZEFA TO PUBLIC; --Publico
GRANT SELECT ON ZEFA TO RM558238; --Pessoa especifica
REVOKE SELECT ON ZEFA FROM PUBLIC; --Revoga o acesso
 
--PARA GRUPO DE PESSOAS
CREATE ROLE RH; --CRIAR UM GRUPO
GRANT SELECT ON ZEFA TO RH; --INSERINDO O GRUPO NA TABELA
GRANT RH TO RM558238, RM555217; --INSERINDO OS USUARIOS PRO GRUPO

SELECT TABLE_NAME FROM USER_TABLES; --Traz todas as tabelas criadas no BD pelo usuário que rodar esse comando
SELECT SYSDATE FROM DUAL; --Retorna a data de hoje
SELECT OWNER, TABLE_NAME FROM ALL_TABLES; --Traz todas as tabelas criadas no BD pelo usuário e as que recebeu permissão de acesso